# -*- coding: utf-8 -*-
"""CodeAlpha_PortfolioManager.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Y-c0PVAl2zb3FhGfQUENCW3sdeeSyRnJ
"""

def display_stocks(stocks):
    print("\nAvailable Stocks:")
    for stock, price in stocks.items():
        print(f"{stock}: ₹{price}")

stocks = {
    "AAPL": 180,
    "TSLA": 250,
    "GOOG": 150,
    "MSFT": 300
}

portfolio = {}
total_investment = 0

print("=" * 50)
print("PERSONAL FINANCE & PORTFOLIO MANAGER")
print("=" * 50)

display_stocks(stocks)

while True:
    stock = input("\nEnter Stock Name (or 'done' to finish): ").upper()

    if stock == "DONE":
        break

    if stock not in stocks:
        print("Invalid Stock!")
        continue

    quantity = int(input("Enter Quantity: "))

    portfolio[stock] = portfolio.get(stock, 0) + quantity

print("\n===== PORTFOLIO SUMMARY =====")

for stock, quantity in portfolio.items():
    value = stocks[stock] * quantity
    total_investment += value

    print(
        f"{stock:<10} Quantity: {quantity:<5} Value: ₹{value}"
    )

print("\nTotal Portfolio Value: ₹", total_investment)

current_value = float(
    input("\nEnter Current Market Value of Portfolio: ₹")
)

profit_loss = current_value - total_investment

if profit_loss > 0:
    print(f"Profit: ₹{profit_loss}")
elif profit_loss < 0:
    print(f"Loss: ₹{-profit_loss}")
else:
    print("No Profit No Loss")

with open("portfolio_report.txt", "w") as file:
    file.write("PORTFOLIO REPORT\n\n")

    for stock, quantity in portfolio.items():
        file.write(f"{stock}: {quantity}\n")

    file.write(
        f"\nTotal Portfolio Value: ₹{total_investment}"
    )

print("\nPortfolio report saved successfully!")